"""change_logo_url_to_text

Revision ID: 6295287caf8f
Revises: 001
Create Date: 2026-07-14 15:22:41.464550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6295287caf8f'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'logo_url',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('organizations', 'logo_url',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('users_clerk_user_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=False)
    op.create_unique_constraint(op.f('users_clerk_user_id_key'), 'users', ['clerk_user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('organizations', 'logo_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
    op.alter_column('clients', 'logo_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
    # ### end Alembic commands ###
